### ISSUE TITLE
Pagination doesn’t work when there are empty paragraphs before an intended page break

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#14]
I’m using DocXWriter.write(pages:to:options:) to write an array of attributed strings with page breaks in between, and noticed that a page break isn’t always inserted. In particular, when a string ends with multiple empty paragraphs in a row, the page break isn’t inserted.

If I trim the attributed strings so that they don’t end with any newline characters, everything behaves as expected. This is a fine workaround for me, but I still think this is a confusing bug.

You can repro by adding two empty lines to the end of the “string” in the testMultiPage() or testMultiPageWriter() tests. With that change, the generated docx file won’t contain any page breaks. I believe this is due to the “early out” in ParagraphElement’s buildRuns(): 
`guard subString.length>0 else{return [AEXMLElement]()}`

**Comment by shinjukunian** [comment]
Hi,

first of all many thanks for catching this and for the detailed description - this made the fix very straightforward. Pull request #15 should fix this issue.
Please let me know if you have any other suggestions or requests.

Cheers from Tokyo

Morten

**Comment by andalman** [comment]
Thanks so much for this fix (and this package)! I really appreciate it.

I do have two other suggestions. I’ll file them, since you asked, but I totally understand if you decide that they fall outside the scope of this package.
