### ISSUE TITLE
Suggestion: simple support for styles

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#17]
I am working on an application that can import a docx file. On import, text that uses particular Word Styles will be imported in specific ways. For instance, text that uses the "Heading 1” style will be imported as a title.

I’d like to be able to export a docx file that looks exactly the same when it is re-imported into my application. To do this perfectly, I need the exported docx to have styles applied to some text.

I imagine that writeDocX(), could take an optional dictionary of Style Information, which would map an identifier (e.g. “Heading1Identifier”) to a dictionary of style information (e.g. [“name”: “Heading 1”, “kind”: “paragraphStyle”, “bold”: “true”]). Then, an attributed string could have an attribute (e.g. NSAttributedString.key.docXStyleIdentifier) that contained the style identifier value (e.g. “Heading1Identifier”). On export, text with that attribute would have the appropriate style applied.

This may be outside the scope of this project, but I figured it couldn’t hurt to submit it.

**Comment by shinjukunian** [comment]
Implemented in #33
