### ISSUE TITLE
Docx is invalid if the written attributed string contains an ampersand (&) or less-than (<) character

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#18]
This is easy to repro using these simple tests:

```
    func testAmpersand() {
        let string="Key & Peele"
        let attributedString=NSAttributedString(string: string)

        testWriteDocX(attributedString: attributedString)
    }

    func testLessThan() {
        let string="0 < 1"
        let attributedString=NSAttributedString(string: string)

        testWriteDocX(attributedString: attributedString)
    }
```

If you then run these tests, they will fail with: [DocXTests.DocXTests testAmpersand] : failed - The file…couldn’t be opened because it isn’t in the correct format.

**Comment by andalman** [comment]
Replacing the `&` with `&amp;` and `<` with `&lt;` would fix this bug. Clients can do this on their end, but it seems better (and safer) to sanitize the string before writing it.

**Comment by andalman** [comment]
One more thing: the DocXOptions (e.g. author, title, etc.) should be sanitized as well. If those strings include ampersands and less-than symbols, then the docx will give a warning when it is opened in Word.

**Comment by andalman** [comment]
I have a fix, and will submit a pull request shortly.

**Comment by shinjukunian** [comment]
again , thank you for catching and fixing this issue. 
In addition, the improved testing seems like a very good idea.
