### ISSUE TITLE
Replacing an existing file does not work

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#20]
When trying to replace an existing docx file with one written by DocX, I get the following error:

```
“[filename].zip” couldn’t be copied to “Desktop” because an item with the same name already exists.
To save the file, either provide a different name, or move aside or delete the existing file, and try again.
```

The reason is because `writeDocX_builtin()` uses `FileManager.default.copyItem()` rather than `replaceItemAt()`. The writing function is all set up to use `replaceItemAt()` since it already creates the temp folder in a location that’s appropriate for the final URL.

(I will submit a pull request for this shortly)

**Comment by shinjukunian** [comment]
thank you for this fix

**Comment by andalman** [comment]
My pleasure!
