### ISSUE TITLE
Long multi-page strings can take an *extremely* long time to write

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#22]
I constructed a test case for a very long “book” that consists of 400 “chapters” of 5,000 words each. When I write it as a docx using `DocXWriter.write(pages:)`, it takes a prohibitively long time: about **100 seconds** on my computer (a 2021 MacBook Pro M1).

Here’s the test:
```
    func testLongBookString() throws {
        // Two paragraphs / 100 words
        let twoParagraphs =
"""
This property contains the space (measured in points) added at the end of the paragraph to separate it from the following paragraph. This value is always nonnegative. The space between paragraphs is determined by adding the previous paragraph’s paragraphSpacing and the current paragraph’s paragraphSpacingBefore.
Specifies the border displayed above a set of paragraphs which have the same set of paragraph border settings. Note that if the adjoining paragraph has identical border settings and a between border is specified, a single between border will be used instead of the bottom border for the first and a top border for the second.
"""
        // Create a "book" that consists of 400 chapters each with 5,000 words
        // (2 million words total).
        let chapterString = String(repeating: twoParagraphs, count: 50)
        let chapterAttributedString = NSAttributedString(string: chapterString)
        let chapters = Array(repeating: chapterAttributedString, count: 400)
        
        let url=self.tempURL.appendingPathComponent(UUID().uuidString + "_myDocument_\(chapterString.prefix(10))").appendingPathExtension("docx")
        
        try DocXWriter.write(pages: chapters, to: url)
        try validateDocX(url: url)
    }
```

Profiling revealed that significant time is spent bridging between NSString/String (and allocating Strings) in `paragraphRanges`.

I have a fix that reduces the time for this test from ~100 seconds to **~1.4s**.

**Comment by shinjukunian** [comment]
thank you for reporting this issue. I never envisioned DocX to be used on this scale. I guess bridging is quite detrimental to performance, and NSAttributedString likely is backed by NSString after all so staying in the ObjC world probably makes sense even though it doesnt feel very 'swifty'. Before I merge this, I just want to make sure that there are no indexing issues for complex scripts / combined characters - this after all was one of the key considerations for Swift string indexing that is somewhat glossed over when using NSRange.

**Comment by andalman** [comment]
I totally understand.

For what it's worth, I ran the tests and they all passed. Also, I don't _think_ this change will cause indexing issues, as the `enumerateSubstrings` method on NSString should behave the same as the one on String. The main difference is that the former uses NSRange while the latter uses Range. And since elsewhere in the code (in `ParagraphElement.swift`), the saved Range was converted to an NSRange, I don't think this should change behavior at all. Can't hurt to test more, though!

**Comment by shinjukunian** [comment]
awesome addition. thank you very much. I added two tests using composite emoji (flags etc.) and Japanese script in #28
