### ISSUE TITLE
Suggestion: docx files should NOT display "Compatibility Mode" when opened in Word

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#26]
When you open a DocX-written file in Word, you'll see "Compatibility Mode" in the title bar. And, if you use **File > Save As** to create a new version of your file, Word will warn you that "you are about to update the file format, which might result in layout changes." 

Compatibility Mode is a file format that allows these docx files to be opened in Word 2010 or earlier. However, it also means that some post-2010 Word features can't be used (unless, of course, you update the file).

Seems like maintaining compatibility with Word 2010 isn't necessary, and it would be preferable for docx files to appear like other "modern" docx files when opened in Word.

I have a fix.

**Comment by shinjukunian** [comment]
Awesome addition, thank you for this.
