### ISSUE TITLE
Underlining doesn't work when color isn't also specified

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#36]
If you have an attributed string and apply `NSAttributedString.Key.underlineStyle` to it, the generated docx will not include that underline. This is because DocX requires that `foregroundColor` must be set, otherwise the `<w:u>` element won't be output.

Since the `w:color` value is optional in the docx, I don't think this should be required. I have a fix ready that makes the `color` argument Optional in the `underlineElement` function.

That said, I'm not sure using the `foregroundColor` is correct either, since `NSAttributedString.Key.underlineColor` exists for the purpose. If existing code relies on this behavior, though, we could have DocX check for the `underlineColor` and, if that isn't found, then use the `foregroundColor` if it exists. Thoughts?

**Comment by shinjukunian** [comment]
Hi
thank you for catching this. It seems my original implementation of underlines was a bit lackadaisical. I guess I was not aware that the `color` was optional for the `<w:u>` element.
I agree with your second suggestion - drop the requirement for a `backgroundcolor` and use `NSAttributedString.Key. underlineColor` for user-specified colors. We should test if the fallback to `foregroundColor ` is required in DocX or if Word does this automatically.

**Comment by andalman** [comment]
I just tested, and it appears that Word does fall back to the text’s color
when no color is explicitly set on the <w:u> element.

I’ll submit a pull request for a change that looks for underlineColor only,
then.

**Comment by shinjukunian** [comment]
Fixed in #37 . Thank you for addressing this!
