### ISSUE TITLE
Other ways to add DocX to the project

### ISSUE THREAD

**Issue by Vaberer** [shinjukunian/DocX#38]
Currently, Only Package is the only way how to install this library. However, it's not always possible to use Packages in large projects due to some reasons. Can you add either manual installation or adding Cocoa Pods option?

**Comment by shinjukunian** [comment]
Hi,
thank you for your message. 
Manual installation has always been possible - just clone the repository and add the DocX framework. The framework does, however, use SPM for its dependencies, which may not be what you want. I have added CocoaPods support in #39. I will merge this PR in the next days. If you want to check it out, please give it a go:
```
pod 'DocX', :git => 'https://github.com/shinjukunian/DocX.git', :branch => 'cocoapods'
```
