### ISSUE TITLE
Multi-page support?

### ISSUE THREAD

**Issue by brianjohnson21** [shinjukunian/DocX#4]
Hello @shinjukunian,

Thank you for this beautiful implementation. Actually I tried to convert a NSMutableAttributed string which has instead other 2 attributed string but I get the .docx document for the first AttributedString.

I did like:

```
let rootAttributedString = NSMutableAttributedString()
rootAttributedString.append(NSAttributedString(string: "blah blah blah 1 ... but more text")
rootAttributedString.append(NSAttributedString(string: "blah blah blah 2 ... more text here also")
```

and then 
`rootAttributedString.writeDocX(to: myURL)`

but the output was the a `.docx` file with `"blah blah blah 1 ... but more text" `only.

Any ideas how to fix this?

B. Regards,
John

**Comment by shinjukunian** [comment]
Hello @brianjohnson21,
thank you for your feedback. I am a bit puzzled - I can't reproduce your problem - using your code gives me a correct .docx. What could you provide more details or a working example to reproduce this behaviour?

Cheers

Morten

**Comment by brianjohnson21** [comment]
> Hello @brianjohnson21,
> thank you for your feedback. I am a bit puzzled - I can't reproduce your problem - using your code gives me a correct .docx. What could you provide more details or a working example to reproduce this behaviour?
> 
> Cheers
> 
> Morten

@shinjukunian thank you for your quick response. Can I contact you via email please? I have some files to share with you - a demo project.

**Comment by brianjohnson21** [comment]
Alright , I applied some changes and it works now. But the question is: For example I have a lot of text (around 2-3 pages), it is possible to split this text and create a multi-page docx file from it?

**Comment by shinjukunian** [comment]
@brianjohnson21 
Sure, that will work. Pagination will be done by Word - NSAttributedString has no concept of a page size, but otherwise you'll get a multipage document as expected (admittedly I have not tested that with _really_ long strings, but a couple pages works fine).
Please let me know if I can be of any further help

Cheers

Morten

**Comment by brianjohnson21** [comment]
@shinjukunian, the question was: it is possible to split the given text to multiple pages? Now, the library puts all the text together.

**Comment by shinjukunian** [comment]
@brianjohnson21 OK, now I understand. 
I had a bit of free time on my hand and implemented this and pushed this the [images branch](https://github.com/shinjukunian/DocX/tree/images). This also adds support for exporting images via NSTextAttachment.

For multipage support, you can use the convenience API of the new DocXWriter
```swift
try DocXWriter.write(pages:[NSAttributedString], to url:URL)
```
To insert page breaks manually, you can add the custom ```NSAttributedString.Key.breakType``` attribute to a range (typically a line break ```\r```) of your string, the value of this attribute is one of the values of the ```BreakType``` ```enum```, typically ```.page```.
I'll do some more testing before I merge into master but you can give it a try now.

Cheers

Morten

**Comment by brianjohnson21** [comment]
thanks @shinjukunian, Appreciate :). Will let you know.

**Comment by mistergrizzlydev** [comment]
Hi @shinjukunian, I tried your implementation but it writes only the first NSAttributedString item (from array) into Word document. Any chance to fix this?

**Comment by mistergrizzlydev** [comment]
Maybe you need to add some operation queue?

**Comment by brianjohnson21** [comment]
@shinjukunian is there a way to contact you?

**Comment by shinjukunian** [comment]
@brianjohnson21  sure, just drop me an email at morten@telethon.jp

**Comment by brianjohnson21** [comment]
thanks @shinjukunian
