### ISSUE TITLE
Images exported to docx should use an extension that matches their format

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#41]
When DocX writes images to the media folder during docx creation, it always uses the “png” extension, regardless of the format of that image.

For instance, if I initialize an NSTextAttachment with a file wrapper that points to a JPEG image (e.g. “image.jpg”), then DocX will export it using a name like “rId3.png”. However, the format for that image is still a JPEG:
```
$ file -I rId3.png 
rId3.png: image/jpeg; charset=binary
```

Instead, it should use an extension that matches the format.

**Comment by shinjukunian** [comment]
Thank you for this PR. I agree that it is a good idea to preserve the original file formats if possible. I have merged your PR with some amendments in #45 .
