### ISSUE TITLE
Can’t build and run tests in `master` branch

### ISSUE THREAD

**Issue by andalman** [shinjukunian/DocX#43]
I think I probably broke this, but I can no longer build and run tests in the `master` branch. (I usually test DocX in the context of my own application, so it’s rare that I build this way these days).

Anyhow, it looks like this is because DocXStyleConfiguration.swift and styles.xml haven’t been added to the project file.

I have a fix.

**Comment by shinjukunian** [comment]
Thank you for fixing this. I guess I have been neglecting the framework targets ever since moving to SPM.
